require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Administrator::CategoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Category. As you add validations to Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Administrator::CategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all categories as @categories" do
      category = Category.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:categories)).to eq([category])
    end
  end

  describe "GET #show" do
    it "assigns the requested administrator_category as @administrator_category" do
      category = Category.create! valid_attributes
      get :show, {:id => category.to_param}, valid_session
      expect(assigns(:administrator_category)).to eq(category)
    end
  end

  describe "GET #new" do
    it "assigns a new administrator_category as @administrator_category" do
      get :new, {}, valid_session
      expect(assigns(:administrator_category)).to be_a_new(Category)
    end
  end

  describe "GET #edit" do
    it "assigns the requested administrator_category as @administrator_category" do
      category = Category.create! valid_attributes
      get :edit, {:id => category.to_param}, valid_session
      expect(assigns(:administrator_category)).to eq(category)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Category" do
        expect {
          post :create, {:administrator_category => valid_attributes}, valid_session
        }.to change(Category, :count).by(1)
      end

      it "assigns a newly created administrator_category as @administrator_category" do
        post :create, {:administrator_category => valid_attributes}, valid_session
        expect(assigns(:administrator_category)).to be_a(Category)
        expect(assigns(:administrator_category)).to be_persisted
      end

      it "redirects to the created administrator_category" do
        post :create, {:administrator_category => valid_attributes}, valid_session
        expect(response).to redirect_to(Category.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved administrator_category as @administrator_category" do
        post :create, {:administrator_category => invalid_attributes}, valid_session
        expect(assigns(:administrator_category)).to be_a_new(Category)
      end

      it "re-renders the 'new' template" do
        post :create, {:administrator_category => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested administrator_category" do
        category = Category.create! valid_attributes
        put :update, {:id => category.to_param, :administrator_category => new_attributes}, valid_session
        category.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested administrator_category as @administrator_category" do
        category = Category.create! valid_attributes
        put :update, {:id => category.to_param, :administrator_category => valid_attributes}, valid_session
        expect(assigns(:administrator_category)).to eq(category)
      end

      it "redirects to the administrator_category" do
        category = Category.create! valid_attributes
        put :update, {:id => category.to_param, :administrator_category => valid_attributes}, valid_session
        expect(response).to redirect_to(category)
      end
    end

    context "with invalid params" do
      it "assigns the administrator_category as @administrator_category" do
        category = Category.create! valid_attributes
        put :update, {:id => category.to_param, :administrator_category => invalid_attributes}, valid_session
        expect(assigns(:administrator_category)).to eq(category)
      end

      it "re-renders the 'edit' template" do
        category = Category.create! valid_attributes
        put :update, {:id => category.to_param, :administrator_category => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested administrator_category" do
      category = Category.create! valid_attributes
      expect {
        delete :destroy, {:id => category.to_param}, valid_session
      }.to change(Category, :count).by(-1)
    end

    it "redirects to the categories list" do
      category = Category.create! valid_attributes
      delete :destroy, {:id => category.to_param}, valid_session
      expect(response).to redirect_to(categories_url)
    end
  end

end
